language: ruby

cache:
  - bundler
services:
  - postgresql
before_script:
  - psql -c 'create database anything_api_test;' -U postgres
test:
  adapter: postgresql
  database: anything_api_test
script:
  - bundle exec rspec spec --format documentation
deploy:
  provider: heroku
  api_key:
    secure: 4ae348e0-7d3b-423b-87cf-bd677321c547
  app: infinite-escarpment-83664
  on:
    repo: Andrey0295/anything-api
# language: ruby
# deploy:
#   provider: heroku

#   script:
#     - bundle install
#   run:
#     - rake db:create
#     - rake db:migrate
#   strategy: git
# rvm:
#  - 2.5.0
# cache:
#  - bundler
# script:
#  - bundle install
#  - bin/rails db:create
#  - bin/rails db:migrate
#  - bundle exec rspec
# services:
#  - postgresql
# # deployment details - add while setting up Heroku
# deploy:
#   provider: heroku:git
#  api_key:
#   secure: "4ae348e0-7d3b-423b-87cf-bd677321c547"
# app: infinite-escarpment-83664
#   on:

